export const data = {
  accounts: [
    {
      account_id: "AJ6ePvQbmRtPwVmrbPzjU115WWQEyguWoRwwR",
      balances: {
        available: 100,
        current: 110,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "0000",
      name: "Plaid Checking",
      official_name: "Plaid Gold Standard 0% Interest Checking",
      subtype: "checking",
      type: "depository",
    },
    {
      account_id: "nveKr3p1jzuJ1oQyEJ5wSaaM66PDp9t8GPkk6",
      balances: {
        available: 200,
        current: 210,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "1111",
      name: "Plaid Saving",
      official_name: "Plaid Silver Standard 0.1% Interest Saving",
      subtype: "savings",
      type: "depository",
    },
    {
      account_id: "mv7qKBLZPkujLG4o7jrgfddBooGVW8u7ARjj4",
      balances: {
        available: null,
        current: 1000,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "2222",
      name: "Plaid CD",
      official_name: "Plaid Bronze Standard 0.2% Interest CD",
      subtype: "cd",
      type: "depository",
    },
    {
      account_id: "9JDxzgVNZAtZ8vG7DZzBcWW7nnpdkqilEz88E",
      balances: {
        available: null,
        current: 410,
        iso_currency_code: "USD",
        limit: 2000,
        unofficial_currency_code: null,
      },
      mask: "3333",
      name: "Plaid Credit Card",
      official_name: "Plaid Diamond 12.5% APR Interest Credit Card",
      subtype: "credit card",
      type: "credit",
    },
    {
      account_id: "wvwNPeA9oju3R9boz3leseeBggpXnvUglA99D",
      balances: {
        available: 43200,
        current: 43200,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "4444",
      name: "Plaid Money Market",
      official_name: "Plaid Platinum Standard 1.85% Interest Money Market",
      subtype: "money market",
      type: "depository",
    },
    {
      account_id: "5kRrl1xGjgh9VzX7y98qsLL7GGAxBbuxpzVVa",
      balances: {
        available: null,
        current: 320.76,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "5555",
      name: "Plaid IRA",
      official_name: null,
      subtype: "ira",
      type: "investment",
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      balances: {
        available: null,
        current: 23631.9805,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "6666",
      name: "Plaid 401k",
      official_name: null,
      subtype: "401k",
      type: "investment",
    },
    {
      account_id: "KJ6Eora9m5twkX7jdwx4SmmAkk6vxGS6mg8qe",
      balances: {
        available: null,
        current: 65262,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "7777",
      name: "Plaid Student Loan",
      official_name: null,
      subtype: "student",
      type: "loan",
    },
    {
      account_id: "rv13x4RyZduJ9kXE5JKwS665zzQLglCyDLw4E",
      balances: {
        available: null,
        current: 56302.06,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "8888",
      name: "Plaid Mortgage",
      official_name: null,
      subtype: "mortgage",
      type: "loan",
    },
  ],
  investment_transactions: [
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -0.22,
      cancel_transaction_id: null,
      date: "2021-03-22",
      fees: 5,
      investment_transaction_id: "W3Vdxe8g95uMzgbx7M1wSppNPgQ6PniWxVMPq",
      iso_currency_code: "USD",
      name: "SELL Cambiar International Equity Institutional",
      price: 25,
      quantity: -0.008902867462305952,
      security_id: "MD9eKXeplrt5yKRlzLqXiavwb6wrdxUb3wdnM",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: 1.1,
      cancel_transaction_id: null,
      date: "2021-03-21",
      fees: 7.99,
      investment_transaction_id: "EJb1QgNE65t4glLxv4qrtKK5l9M6lkUjzNQgz",
      iso_currency_code: "USD",
      name: "BUY Achillion Pharmaceuticals Inc.",
      price: 2.16,
      quantity: 0.520877874205698,
      security_id: "KDwjlXj1Rqt58dVvmzRguxJybmyQL8FgeWWAy",
      subtype: "buy",
      type: "buy",
      unofficial_currency_code: null,
    },
    {
      account_id: "5kRrl1xGjgh9VzX7y98qsLL7GGAxBbuxpzVVa",
      amount: 46.32,
      cancel_transaction_id: null,
      date: "2021-03-20",
      fees: 5,
      investment_transaction_id: "pvZzBdLpe3uLJ74VvLPahQQLqd31qGSDedgJK",
      iso_currency_code: "USD",
      name: "BUY NFLX DERIVATIVE",
      price: 0.01,
      quantity: 4211.152345617756,
      security_id: "8E4L9XLl6MudjEpwPAAgivmdZRdBPJuvMPlPb",
      subtype: "buy",
      type: "buy",
      unofficial_currency_code: null,
    },
    {
      account_id: "5kRrl1xGjgh9VzX7y98qsLL7GGAxBbuxpzVVa",
      amount: -1200,
      cancel_transaction_id: null,
      date: "2021-03-20",
      fees: 0,
      investment_transaction_id: "ovQrzkXN7BuZ5z4EaZRWc44ZPp7aP3tXAm9pr",
      iso_currency_code: "USD",
      name:
        "INVBANKTRAN DEP CO CONTR CURRENT YR EMPLOYER CU CO CONTR CURRENT YR EMPLOYER CUR YR",
      price: 0,
      quantity: 0,
      security_id: "d6ePmbPxgWCWmMVv66q9iPV94n91vMtov5Are",
      subtype: "deposit",
      type: "cash",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -14961.99,
      cancel_transaction_id: null,
      date: "2021-03-19",
      fees: 0,
      investment_transaction_id: "8gA3r8wVQkuPVpMJEPWzURRw8G3Q8Mix5BaZN",
      iso_currency_code: "USD",
      name: "SELL Southside Bancshares Inc.",
      price: 34.12,
      quantity: -430.80867509953123,
      security_id: "eW4jmnjd6AtjxXVrjmj6SX1dNEdZp3Cy8RnRQ",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
    {
      account_id: "5kRrl1xGjgh9VzX7y98qsLL7GGAxBbuxpzVVa",
      amount: -2066.58,
      cancel_transaction_id: null,
      date: "2021-03-19",
      fees: 0,
      investment_transaction_id: "LJ6Wkzjy95tjgJwnAjdofDDgepmVe7iLB58el",
      iso_currency_code: "USD",
      name: "SELL iShares Inc MSCI Brazil",
      price: 41.62,
      quantity: -49.02909689729298,
      security_id: "abJamDazkgfvBkVGgnnLUWXoxnomp5up8llg4",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: 466.71,
      cancel_transaction_id: null,
      date: "2021-03-18",
      fees: 1.95,
      investment_transaction_id: "god8gLAZ35t8q3dnm8RJSllR3dKD3WFl9JDLP",
      iso_currency_code: "USD",
      name: "BUY FIDELITY INDEX 1055",
      price: 13.57,
      quantity: 33.99208384602773,
      security_id: "nnmo8doZ4lfKNEDe3mPJipLGkaGw3jfPrpxoN",
      subtype: "buy",
      type: "buy",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -0.1,
      cancel_transaction_id: null,
      date: "2021-03-18",
      fees: 0,
      investment_transaction_id: "AJ6ePvQbmRtPwVmrbPzjU11KX5kqXrSWMmw4e",
      iso_currency_code: "USD",
      name: "INVBANKTRAN DEP INTEREST EARNED INTEREST EARNED",
      price: 0,
      quantity: 0,
      security_id: "d6ePmbPxgWCWmMVv66q9iPV94n91vMtov5Are",
      subtype: "interest",
      type: "cash",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -8.72,
      cancel_transaction_id: null,
      date: "2021-02-23",
      fees: 0,
      investment_transaction_id: "ywyj7Z3zpehr6aDE5r8oUyyrJ598JZhrMBdKN",
      iso_currency_code: "USD",
      name: "INCOME DIV DIVIDEND RECEIVED",
      price: 0,
      quantity: 0,
      security_id: "eW4jmnjd6AtjxXVrjmj6SX1dNEdZp3Cy8RnRQ",
      subtype: "dividend",
      type: "cash",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -1289.01,
      cancel_transaction_id: null,
      date: "2021-02-22",
      fees: 7.99,
      investment_transaction_id: "bZr1M93QqJu8oRrEz85DSqq3ogvyo7TGPeLoM",
      iso_currency_code: "USD",
      name: "SELL Matthews Pacific Tiger Fund Insti Class",
      price: 27.53,
      quantity: -47.74104242992852,
      security_id: "JDdP7XPMklt5vwPmDN45t3KAoWAPmjtpaW7DP",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -203,
      cancel_transaction_id: null,
      date: "2021-02-22",
      fees: 3.99,
      investment_transaction_id: "mv7qKBLZPkujLG4o7jrgfddjlBQ4lEC7kaj4B",
      iso_currency_code: "USD",
      name: "SELL Trp Equity Income",
      price: 20.3,
      quantity: -10,
      security_id: "lngLy3Le7vflLnAzKqwZs19l6bl8P5H1jG9Zz",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: 7.7,
      cancel_transaction_id: null,
      date: "2021-02-21",
      fees: 7.99,
      investment_transaction_id: "nveKr3p1jzuJ1oQyEJ5wSaaJXMr4XbU8D4k3a",
      iso_currency_code: "USD",
      name: "BUY DoubleLine Total Return Bond Fund",
      price: 10.42,
      quantity: 0.7388014749727547,
      security_id: "NDVQrXQoqzt5v3bAe8qRt4A7mK7wvZCLEBBJk",
      subtype: "buy",
      type: "buy",
      unofficial_currency_code: null,
    },
    {
      account_id: "l6jlkzW5NKirq6REnrWXUbbZMM4p1BiLr1WW9",
      amount: -0.22,
      cancel_transaction_id: null,
      date: "2021-02-20",
      fees: 5,
      investment_transaction_id: "GJApME3Bm5tW6m89wWr3INNDGZLxG7CWwd9Gr",
      iso_currency_code: "USD",
      name: "SELL Cambiar International Equity Institutional",
      price: 25,
      quantity: -0.008902867462305952,
      security_id: "MD9eKXeplrt5yKRlzLqXiavwb6wrdxUb3wdnM",
      subtype: "sell",
      type: "sell",
      unofficial_currency_code: null,
    },
  ],
  item: {
    available_products: ["assets", "auth", "balance", "identity", "income"],
    billed_products: ["investments", "transactions"],
    consent_expiration_time: null,
    error: null,
    institution_id: "ins_54",
    item_id: "BJAQjgldm6t8Zo1zR8G7SKKVQdgyJPU7X7KNL",
    update_type: "background",
    webhook: "",
  },
  request_id: "XQDswp8g6eAX9pe",
  securities: [
    {
      close_price: 0.011,
      close_price_as_of: null,
      cusip: null,
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: null,
      iso_currency_code: "USD",
      name: "Nflx Feb 01'18 $355 Call",
      proxy_security_id: null,
      security_id: "8E4L9XLl6MudjEpwPAAgivmdZRdBPJuvMPlPb",
      sedol: null,
      ticker_symbol: "NFLX180201C00355000",
      type: "derivative",
      unofficial_currency_code: null,
    },
    {
      close_price: 27,
      close_price_as_of: null,
      cusip: "577130834",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US5771308344",
      iso_currency_code: "USD",
      name: "Matthews Pacific Tiger Fund Insti Class",
      proxy_security_id: null,
      security_id: "JDdP7XPMklt5vwPmDN45t3KAoWAPmjtpaW7DP",
      sedol: null,
      ticker_symbol: "MIPTX",
      type: "mutual fund",
      unofficial_currency_code: null,
    },
    {
      close_price: 2.11,
      close_price_as_of: null,
      cusip: "00448Q201",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US00448Q2012",
      iso_currency_code: "USD",
      name: "Achillion Pharmaceuticals Inc.",
      proxy_security_id: null,
      security_id: "KDwjlXj1Rqt58dVvmzRguxJybmyQL8FgeWWAy",
      sedol: null,
      ticker_symbol: "ACHN",
      type: "equity",
      unofficial_currency_code: null,
    },
    {
      close_price: 24.5,
      close_price_as_of: null,
      cusip: "00769G543",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US00769G5430",
      iso_currency_code: "USD",
      name: "Cambiar International Equity Institutional",
      proxy_security_id: null,
      security_id: "MD9eKXeplrt5yKRlzLqXiavwb6wrdxUb3wdnM",
      sedol: null,
      ticker_symbol: "CAMYX",
      type: "mutual fund",
      unofficial_currency_code: null,
    },
    {
      close_price: 10.42,
      close_price_as_of: null,
      cusip: "258620103",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US2586201038",
      iso_currency_code: "USD",
      name: "DoubleLine Total Return Bond Fund",
      proxy_security_id: null,
      security_id: "NDVQrXQoqzt5v3bAe8qRt4A7mK7wvZCLEBBJk",
      sedol: null,
      ticker_symbol: "DBLTX",
      type: "mutual fund",
      unofficial_currency_code: null,
    },
    {
      close_price: 27,
      close_price_as_of: null,
      cusip: "779547108",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US7795471082",
      iso_currency_code: "USD",
      name: "T. Rowe Price Equity Income",
      proxy_security_id: null,
      security_id: "PDRMBVM8r3t5BA9NmJdKfPolGqlg8dtEGB37n",
      sedol: null,
      ticker_symbol: "PRFDX",
      type: "mutual fund",
      unofficial_currency_code: null,
    },
    {
      close_price: 42.15,
      close_price_as_of: null,
      cusip: "464286400",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US4642864007",
      iso_currency_code: "USD",
      name: "iShares Inc MSCI Brazil",
      proxy_security_id: null,
      security_id: "abJamDazkgfvBkVGgnnLUWXoxnomp5up8llg4",
      sedol: null,
      ticker_symbol: "EWZ",
      type: "etf",
      unofficial_currency_code: null,
    },
    {
      close_price: 1,
      close_price_as_of: null,
      cusip: null,
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: true,
      isin: null,
      iso_currency_code: "USD",
      name: "U S Dollar",
      proxy_security_id: null,
      security_id: "d6ePmbPxgWCWmMVv66q9iPV94n91vMtov5Are",
      sedol: null,
      ticker_symbol: null,
      type: "cash",
      unofficial_currency_code: null,
    },
    {
      close_price: 34.73,
      close_price_as_of: null,
      cusip: "84470P109",
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: "US84470P1093",
      iso_currency_code: "USD",
      name: "Southside Bancshares Inc.",
      proxy_security_id: null,
      security_id: "eW4jmnjd6AtjxXVrjmj6SX1dNEdZp3Cy8RnRQ",
      sedol: null,
      ticker_symbol: "SBSI",
      type: "equity",
      unofficial_currency_code: null,
    },
    {
      close_price: 20,
      close_price_as_of: null,
      cusip: null,
      institution_id: null,
      institution_security_id: null,
      is_cash_equivalent: false,
      isin: null,
      iso_currency_code: "USD",
      name: "Trp Equity Income",
      proxy_security_id: "PDRMBVM8r3t5BA9NmJdKfPolGqlg8dtEGB37n",
      security_id: "lngLy3Le7vflLnAzKqwZs19l6bl8P5H1jG9Zz",
      sedol: null,
      ticker_symbol: null,
      type: "mutual fund",
      unofficial_currency_code: null,
    },
    {
      close_price: 13.73,
      close_price_as_of: null,
      cusip: null,
      institution_id: "ins_54",
      institution_security_id: "NHX105509",
      is_cash_equivalent: false,
      isin: null,
      iso_currency_code: "USD",
      name: "NH PORTFOLIO 1055 (FIDELITY INDEX)",
      proxy_security_id: null,
      security_id: "nnmo8doZ4lfKNEDe3mPJipLGkaGw3jfPrpxoN",
      sedol: null,
      ticker_symbol: "NHX105509",
      type: "etf",
      unofficial_currency_code: null,
    },
  ],
  total_investment_transactions: 13,
  status_code: 200,
};
