export const nailColorData = [
  { name: "Snowfalling for You", colorGroup: "Pink", hexValue: "e7a3a0" },
  { name: "This Shade is Ornamental!", colorGroup: "Pink", hexValue: "c67a82" },
  { name: "Merry in Cranberry", colorGroup: "Pink", hexValue: "953272" },
  { name: "Baby, Take a Vow", colorGroup: "Pink", hexValue: "fce3ed" },
  { name: "Feeling Optiprismic", colorGroup: "Purple", hexValue: "b52c93" },
  { name: "Throw Me A Kiss", colorGroup: "Pink", hexValue: "eeecef" },
  {
    name: "Getting Nadi On My Honeymoon",
    colorGroup: "Pink",
    hexValue: "eda4be",
  },
  { name: "Two-timing the Zones", colorGroup: "Pink", hexValue: "e367a5" },
  { name: "Aurora Berry-alis", colorGroup: "Pink", hexValue: "9b3257" },
  {
    name: "I’ll Have a Gin & Tectonic",
    colorGroup: "Pink",
    hexValue: "d57d77",
  },
  { name: "Aloha from OPI", colorGroup: "Pink", hexValue: "e6282b" },
  { name: "Beyond the Pale Pink", colorGroup: "Pink", hexValue: "fcf0f4" },
  { name: "Defy Explanation", colorGroup: "Pink", hexValue: "c75879" },
  { name: "From Here To Eternity", colorGroup: "Pink", hexValue: "fe3869" },
  { name: "Girl Without Limits", colorGroup: "Pink", hexValue: "ea529e" },
  { name: "Indefinitely Baby", colorGroup: "Pink", hexValue: "f7bfde" },
  { name: "It’s Pink P.M.", colorGroup: "Pink", hexValue: "fbd5df" },
  { name: "Patience Pays Off", colorGroup: "Pink", hexValue: "fcdfde" },
  { name: "Pretty Pink Perseveres", colorGroup: "Pink", hexValue: "fed0db" },
  { name: "Rose Against Time", colorGroup: "Pink", hexValue: "f27da8" },
  {
    name: "Running With The In-Finite Crowd",
    colorGroup: "Pink",
    hexValue: "f11a5e",
  },
  { name: "She Went On And On And On", colorGroup: "Pink", hexValue: "ff255c" },
  { name: "You're Blushing Again", colorGroup: "Pink", hexValue: "f9c4bf" },
  {
    name: "A-Rose at Dawn...Broke by Noon",
    colorGroup: "Pink",
    hexValue: "b24266",
  },
  { name: "Aphrodite's Pink Nightie", colorGroup: "Pink", hexValue: "f798b5" },
  { name: "Chicago Champaign Toast", colorGroup: "Pink", hexValue: "a86f76" },
  { name: "Cozu-Melted in The Sun", colorGroup: "Pink", hexValue: "ff8c96" },
  { name: "Dutch Tulips", colorGroup: "Pink", hexValue: "c91631" },
  { name: "It's a Girl!", colorGroup: "Pink", hexValue: "f0d1d6" },
  { name: "La Paz-itively Hot", colorGroup: "Pink", hexValue: "c7327c" },
  { name: "Mod About You", colorGroup: "Pink", hexValue: "efaecf" },
  { name: "My Address Is “Hollywood”", colorGroup: "Pink", hexValue: "c04c61" },
  { name: "Not So Bora-Bora-ing Pink", colorGroup: "Pink", hexValue: "be5f73" },
  { name: "Passion", colorGroup: "Pink", hexValue: "fdddd2" },
  { name: "Pompeii Purple", colorGroup: "Pink", hexValue: "b7317d" },
  { name: "Princesses Rule!", colorGroup: "Pink", hexValue: "f09eb5" },
  { name: "Shorts Story", colorGroup: "Pink", hexValue: "d94b8d" },
  { name: "Strawberry Margarita", colorGroup: "Pink", hexValue: "d91c5b" },
  { name: "Suzi Nails New Orleans", colorGroup: "Pink", hexValue: "f17ca5" },
  { name: "Sweet Heart", colorGroup: "Pink", hexValue: "eab2b3" },
  { name: "Tickle my France-y", colorGroup: "Pink", hexValue: "be9ea1" },
  { name: "Lisbon Wants Moor OPI", colorGroup: "Pink", hexValue: "ffe5e5" },
  {
    name: "Made It To the Seventh Hill!",
    colorGroup: "Pink",
    hexValue: "b77a76",
  },
  {
    name: "No Turning Back From Pink Street",
    colorGroup: "Pink",
    hexValue: "ed499b",
  },
  { name: "Tagus in That Selfie!", colorGroup: "Pink", hexValue: "e691b3" },
  { name: "You've Got Nata On Me", colorGroup: "Pink", hexValue: "e68987" },
  { name: "Telenovela Me About It", colorGroup: "Pink", hexValue: "c9427f" },
  {
    name: "Lima Tell You About This Color!",
    colorGroup: "Pink",
    hexValue: "f09cb3",
  },
  { name: "Machu Peach-u", colorGroup: "Pink", hexValue: "eabcb3" },
  {
    name: "Somewhere Over the Rainbow Mountains",
    colorGroup: "Pink",
    hexValue: "c99490",
  },
  { name: "Suzi Will Quechua Later!", colorGroup: "Pink", hexValue: "c588a8" },
  {
    name: "All Your Dreams in Vending Machines",
    colorGroup: "Pink",
    hexValue: "860965",
  },
  { name: "Another Ramen-tic Evening", colorGroup: "Pink", hexValue: "e1a6bf" },
  { name: "Arigato from Tokyo", colorGroup: "Pink", hexValue: "c16c99" },
  {
    name: "Hurry-juku Get This Color!",
    colorGroup: "Pink",
    hexValue: "c42567",
  },
  { name: "Rice Rice Baby", colorGroup: "Pink", hexValue: "c59098" },
  { name: "Knowledge is Flower", colorGroup: "Orange", hexValue: "ca7a95" },
  { name: "Emflowered", colorGroup: "Pink", hexValue: "f989d3" },
  {
    name: "Let Nature Take Its Quartz",
    colorGroup: "Pink",
    hexValue: "fecdd0",
  },
  { name: "Thistle Make You Bloom", colorGroup: "Pink", hexValue: "b7319e" },
  { name: "Big Bloom Energy", colorGroup: "Orange", hexValue: "f75a75" },
  { name: "We Canyon Do Better", colorGroup: "Orange", hexValue: "fabebe" },
  { name: "For What It’s Earth", colorGroup: "Brown", hexValue: "cb7f8b" },
  { name: "Snowfalling for You", colorGroup: "Pink", hexValue: "e7a3a0" },
  { name: "This Shade is Ornamental!", colorGroup: "Pink", hexValue: "c67a82" },
  { name: "Merry in Cranberry", colorGroup: "Pink", hexValue: "953272" },
  { name: "Baby, Take a Vow", colorGroup: "Pink", hexValue: "fce3ed" },
  { name: "She's a Prismaniac", colorGroup: "Pink", hexValue: "db4181" },
  { name: "Throw Me A Kiss", colorGroup: "Pink", hexValue: "eeecef" },
  {
    name: "A-Rose at Dawn...Broke by Noon",
    colorGroup: "Pink",
    hexValue: "b24266",
  },
  { name: "Aphrodite's Pink Nightie", colorGroup: "Pink", hexValue: "d98dac" },
  { name: "California Raspberry", colorGroup: "Pink", hexValue: "c02244" },
  { name: "Charged Up Cherry", colorGroup: "Pink", hexValue: "ce4068" },
  { name: "Chicago Champaign Toast", colorGroup: "Pink", hexValue: "a86f76" },
  { name: "Cozu-melted in the Sun", colorGroup: "Pink", hexValue: "ff8c96" },
  { name: "Dutch Tulips", colorGroup: "Pink", hexValue: "cc285c" },
  { name: "ElePhantastic Pink", colorGroup: "Pink", hexValue: "d36276" },
  { name: "Hawaiian Orchid", colorGroup: "Pink", hexValue: "e4adc0" },
  { name: "Hotter than You Pink", colorGroup: "Pink", hexValue: "bf4e94" },
  { name: "I Think In Pink", colorGroup: "Pink", hexValue: "e079a7" },
  { name: "It's a Girl!", colorGroup: "Pink", hexValue: "f0d1d6" },
  { name: "Koala Bear-y", colorGroup: "Pink", hexValue: "cb256f" },
  { name: "La Paz-itively Hot", colorGroup: "Pink", hexValue: "d25895" },
  { name: "Not So Bora-Bora-ing Pink", colorGroup: "Pink", hexValue: "d58497" },
  { name: "Passion", colorGroup: "Pink", hexValue: "f0d1cf" },
  { name: "Pink Flamenco", colorGroup: "Pink", hexValue: "ce3b80" },
  { name: "Pink-ing of You", colorGroup: "Pink", hexValue: "f08dc8" },
  { name: "Pompeii Purple", colorGroup: "Pink", hexValue: "ce2e79" },
  { name: "Princesses Rule!", colorGroup: "Pink", hexValue: "cea1ab" },
  { name: "Rosy Future", colorGroup: "Pink", hexValue: "e7b3c9" },
  { name: "Shorts Story", colorGroup: "Pink", hexValue: "d366a0" },
  { name: "Strawberry Margarita", colorGroup: "Pink", hexValue: "ef5d8e" },
  { name: "Suzi Shops & Island Hops", colorGroup: "Pink", hexValue: "ffabcd" },
  { name: "Sweet Heart", colorGroup: "Pink", hexValue: "f5ddd3" },
  { name: "That's Berry Daring", colorGroup: "Pink", hexValue: "cd3184" },
  { name: "Tickle My France-y", colorGroup: "Pink", hexValue: "be9ea1" },
  { name: "Tutti Frutti Tonga", colorGroup: "Pink", hexValue: "ed8787" },
  {
    name: "Getting Nadi On My Honeymoon",
    colorGroup: "Pink",
    hexValue: "eda4be",
  },
  { name: "Two-Timing the Zones", colorGroup: "Pink", hexValue: "e366a7" },
  { name: "Aurora Berry-alis", colorGroup: "Pink", hexValue: "ae4268" },
  {
    name: "I’ll Have a Gin & Tectonic",
    colorGroup: "Pink",
    hexValue: "d57d77",
  },
  { name: "Lisbon Wants Moor OPI", colorGroup: "Pink", hexValue: "ffe5e5" },
  {
    name: "Made It To the Seventh Hill!",
    colorGroup: "Pink",
    hexValue: "b77a76",
  },
  {
    name: "No Turning Back From Pink Street",
    colorGroup: "Pink",
    hexValue: "ed499b",
  },
  { name: "Tagus in That Selfie!", colorGroup: "Pink", hexValue: "e691b3" },
  { name: "You've Got Nata On Me", colorGroup: "Pink", hexValue: "e68987" },
  { name: "Telenovela Me About It", colorGroup: "Pink", hexValue: "c9427f" },
  { name: "Shellmates Forever!", colorGroup: "Pink", hexValue: "d5b3bd" },
  { name: "Let Me Bayou a Drink", colorGroup: "Pink", hexValue: "f4cdd4" },
  { name: "Suzi Nails New Orleans", colorGroup: "Pink", hexValue: "ff8aaf" },
  {
    name: "Lima Tell You About This Color!",
    colorGroup: "Pink",
    hexValue: "f09cb3",
  },
  { name: "Machu Peach-u", colorGroup: "Pink", hexValue: "eabcb3" },
  {
    name: "Somewhere Over the Rainbow Mountains",
    colorGroup: "Pink",
    hexValue: "c99490",
  },
  { name: "Suzi Will Quechua Later!", colorGroup: "Pink", hexValue: "c588a8" },
  {
    name: "All Your Dreams in Vending Machines",
    colorGroup: "Pink",
    hexValue: "860965",
  },
  { name: "Another Ramen-tic Evening", colorGroup: "Pink", hexValue: "e1a6bf" },
  { name: "Arigato from Tokyo", colorGroup: "Pink", hexValue: "c16c99" },
  {
    name: "Hurry-juku Get This Color!",
    colorGroup: "Pink",
    hexValue: "c42567",
  },
  { name: "Rice Rice Baby", colorGroup: "Pink", hexValue: "c59098" },
] as const;
